version: '2'
services:
    applicationsupportdashboard-app:
        image: applicationsupportdashboard
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://applicationsupportdashboard-mariadb:3306/applicationsupportdashboard
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    applicationsupportdashboard-mariadb:
        extends:
            file: mariadb.yml
            service: applicationsupportdashboard-mariadb
